#!/bin/sh
uwsgi -H /home/eastein/pyenvs/Maker-Network -log-x-forwarded-for -s /tmp/runshit/mkn.uwsgi.sock -w makernetwork_wsgi -b16383 --post-buffering=16384 --enable-threads --log-slow 300 --log-4xx --log-5xx -m
exit $?
